services:
  # Backend API service
  - type: web
    name: iching-backend
    runtime: python
    plan: free
    buildCommand: cd divination && pip install poetry && poetry install
    startCommand: cd divination && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        fromService:
          name: iching-frontend
          type: web
          property: url

  # Frontend service
  - type: web
    name: iching-frontend
    runtime: node
    plan: free
    buildCommand: cd packages/frontend && npm install && npm run build
    startCommand: cd packages/frontend && npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        fromService:
          name: iching-backend
          type: web
          property: url
