# Render Blueprint for I Ching application

services:
  # Backend API service
  - type: web
    name: iching-backend
    runtime: python
    plan: free
    buildCommand: |
      ls -la
      if [ -f divination/requirements.txt ]; then
        echo "Installing from existing requirements.txt"
        cat divination/requirements.txt
        pip install -r divination/requirements.txt
      else
        echo "Creating requirements.txt"
        echo "fastapi>=0.109.2
        uvicorn>=0.27.0
        pydantic>=2.5.3
        python-dotenv>=1.0.1
        typing-extensions>=4.9.0
        argparse>=1.4.0
        gunicorn>=23.0.0" > requirements.txt
        pip install -r requirements.txt
      fi
    startCommand: cd divination && PYTHONPATH=$PYTHONPATH:$(pwd) python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: PORT
        value: "8000"
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "https://iching-frontend.onrender.com"

  # Frontend service
  - type: web
    name: iching-frontend
    runtime: node
    plan: free
    buildCommand: cd packages/frontend && npm install && npm run build
    startCommand: cd packages/frontend && npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: NODE_VERSION
        value: "18.0.0"
      - key: PORT
        value: "10000"
      - key: VITE_API_URL
        value: "https://iching-backend.onrender.com"
