[lint]
select = ["E", "F", "I", "W", "R"] # Enable common error, warning, and isort rules
ignore = [] # Add specific error codes to ignore

[format]
indent-style = "space" # Set the indentation style
quote-style = "double" # Set the quote style
preview = true # Enable preview features
docstring-code-line-length = 120 # Set the maximum line length for docstrings
docstring-code-format = true # Format docstrings with code samples




[isort]
combine-as-imports = true # Combine as imports
force-sort-within-sections = true # Force sort within sections
known-first-party = ["app"] # Add your project's package name